package academy.devdojo.estudojava.javacore.Oexception.runtime.test;

public class RuntimeExceptionTest02 {
    public static void main(String[] args) {
        try {
            divisao(1, 0);
        }catch (RuntimeException e){
            e.printStackTrace();
        }
        //sem tratamento isso n찾o vai funcionar
        System.out.println("C처digo finalizado");
    }

    /**
     *
     * @param a
     * @param b n찾o pode ser zero
     * @return
     * @throws IllegalArgumentException caso b seja zero
     */
    private static int divisao(int a, int b) {
        if(b == 0){
            throw new IllegalArgumentException("Argumento ilegal, n찾o pode ser 0");
        }
        return a/b;
    }
}
